image: amazonlinux

before_script:
  - sudo yum install -y yum-utils shadow-utils unzip
  - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - sudo yum -y install packer terraform
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install

stages:
  - init
  - build
 
init:
  stage: init
  script:
    - packer init .

build:
  stage: build
  script:
    - packer build .
  dependencies:
    - init
  only:
    - main
