image: amazonlinux

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

before_script:
  - yum install -y yum-utils shadow-utils unzip
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install packer terraform
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install

stages:
  - init
  - build
 
init:
  stage: init
  script:
    - packer init -upgrade .
  artifacts:
    paths:
      - ./.packer.d/plugins/ # Save the plugins directory as an artifact

build:
  stage: build
  script:
    - packer build .
  dependencies:
    - init
  only:
    - main
