image: amazonlinux

before_script:
  - yum install -y yum-utils shadow-utils unzip
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install packer terraform
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install

stages:
  - init
  - build
 
init:
  stage: init
  script:
    - packer init .

build:
  stage: build
  script:
    - packer build .
  dependencies:
    - init
  only:
    - main
