image: amazonlinux

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_ADMIN
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_ADMIN
  AWS_DEFAULT_REGION: "ap-south-1"  # Adjust this to your preferred region

before_script:
  - yum install -y yum-utils shadow-utils unzip
  - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  - yum -y install packer terraform
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install
  #  Optionally configure AWS CLI explicitly (usually not needed if environment variables are set)
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID_ADMIN
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_ADMIN
  - aws configure set region $AWS_DEFAULT_REGION

stages:
  - init
  - build

init:
  stage: init
  script:
    - packer init -upgrade .
  artifacts:
    paths:
      - ./.packer.d/plugins/ # Save the plugins directory as an artifact

build:
  stage: build
  script:
    - packer init -upgrade .  # Ensures plugins are available in the build stage
    - packer build .
  dependencies:
    - init
  only:
    - main
