# Use a Docker-in-Docker service for Docker commands
image: docker:24.0.2

services:
  - docker:24.0.2-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_BUILDKIT: 1  # Enable Docker BuildKit for improved security and performance
  DOCKER_CONTENT_TRUST: 1  # Enable Docker Content Trust
  REGISTRY: $CI_REGISTRY  # GitLab's Container Registry
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA  # Use commit SHA as the tag

stages:
  - build
  - push

before_script:
  # Install Docker and log in to GitLab Container Registry
  - apk add --no-cache curl
  - curl -fsSL https://get.docker.com | sh
  # Login to GitLab Container Registry using predefined CI variables
  - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG --progress=plain .
  only:
    - main  # Adjust this to your preferred branch

push:
  stage: push
  script:
    - docker push $IMAGE_TAG
  only:
    - main  # Adjust this to your preferred branch
